options(show.error.locations = TRUE)
#source("renv/activate.R")
library(here)
AnnotationHub::setAnnotationHubOption("CACHE", here("data", "raw", ".myHub"))
AnnotationHub::setAnnotationHubOption("ASK", FALSE)
